stages:
  - build
  - test
  - release

variables: 
  CONTAINER_TEST_IMAGE: docker.mawalabs.de/floggl/docker-nginx-php:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: docker.mawalabs.de/floggl/docker-nginx-php:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.mawalabs.de

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test-nginx:
  stage: test
  script:
    - CONTAINER=$(docker run -d $CONTAINER_TEST_IMAGE)
    - sleep 5
    - docker exec $CONTAINER /usr/bin/curl localhost
    - docker rm -f $CONTAINER

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
