image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables: 
  CONTAINER_TEST_IMAGE: registry.gitlab.com/floggl/docker-nginx-php:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/floggl/docker-nginx-php:latest

before_script:
  - docker login -u floggl-deploy-bot -p $DEPLOY_BOT_PW registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test-nginx:
  stage: test
  script:
    - CONTAINER=$(docker run -d $CONTAINER_TEST_IMAGE)
    - sleep 5
    - docker exec $CONTAINER /usr/bin/curl localhost
    - docker rm -f $CONTAINER

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
